## numpy基础运算Part1

### 基础运算

In [11]:
import numpy as np
array_a = np.array([10,20,30,40])
array_b = np.arange(4)
print(array_a + array_b)
print(array_a - array_b)
print(array_b**2)
print(array_a*array_b)

[10 21 32 43]
[10 19 28 37]
[0 1 4 9]
[  0  20  60 120]


### 函数运算

In [16]:
array_c = np.sin(array_a)#弧度制
print(array_c)
print(array_c > 0.5)

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[False  True False  True]


### 对多维数组的相乘操作

In [19]:
a = np.array([[0,1],[1,0]])
b = np.arange(4).reshape((2,2))
print(a)
print(b)
print(np.dot(a,b))

[[0 1]
 [1 0]]
[[0 1]
 [2 3]]
[[2 3]
 [0 1]]


### sum( ),min( ),max( )函数的使用

In [24]:
a = np.random.random((2,4))
print(a)
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.sum(a,axis=0))#axis取0，按列为查找单元；axis取1，按行为查找单元

[[0.45888926 0.28782931 0.99265402 0.70312526]
 [0.9912903  0.05823525 0.62063476 0.42645191]]
4.539110077653827
0.058235248833443665
0.9926540229313691
[1.45017956 0.34606456 1.61328878 1.12957717]


## numpy基础运算Part2

### argmin( )和argmax( )函数

In [30]:
a = np.random.random(16).reshape((4,4))
print(a)
b = np.argmin(a)
print(b)
b = np.argmax(a)
print(b)


[[0.51239732 0.05112424 0.04564404 0.92028433]
 [0.60576448 0.96594601 0.8676181  0.65661195]
 [0.44636888 0.19554481 0.39373629 0.40745677]
 [0.47097489 0.13882368 0.73208829 0.00098322]]
15
5


### 求均值

In [31]:
print(np.mean(a))
print(np.average(a))

0.46321045695303864
0.46321045695303864


### cumsum( )函数

In [34]:
a = np.arange(16)
print(a)
print(np.cumsum(a))#累加函数

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120]


### diff( )函数

In [40]:
a = np.arange(16)
print(a)
print(np.diff(a))
b = np.arange(0,16,2)
print(b)
print(np.diff(b))# 累差函数

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[ 0  2  4  6  8 10 12 14]
[2 2 2 2 2 2 2]


### sort( )函数

In [48]:
a = np.random.random(16)
print(a)
print(np.sort(a))
b = a.reshape((4,4))
print(b)
print(np.sort(b))#排序函数

[0.34234744 0.1344384  0.33469275 0.95557385 0.99471146 0.07069196
 0.02916013 0.4494076  0.12788424 0.94421766 0.99178646 0.32644535
 0.76469607 0.27488995 0.02921415 0.772519  ]
[0.02916013 0.02921415 0.07069196 0.12788424 0.1344384  0.27488995
 0.32644535 0.33469275 0.34234744 0.4494076  0.76469607 0.772519
 0.94421766 0.95557385 0.99178646 0.99471146]
[[0.34234744 0.1344384  0.33469275 0.95557385]
 [0.99471146 0.07069196 0.02916013 0.4494076 ]
 [0.12788424 0.94421766 0.99178646 0.32644535]
 [0.76469607 0.27488995 0.02921415 0.772519  ]]
[[0.1344384  0.33469275 0.34234744 0.95557385]
 [0.02916013 0.07069196 0.4494076  0.99471146]
 [0.12788424 0.32644535 0.94421766 0.99178646]
 [0.02921415 0.27488995 0.76469607 0.772519  ]]


### 矩阵的转置

In [53]:
a = np.arange(16).reshape((4,4))
print(a)
print(a.T)
print(np.transpose(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
