# numpy学习


## numpy属性
****************
1. 基础知识

    `ndim`:维度

    `shape`:行数和列数

    `size`:元素个数
    
***********

2. 具体操作

    使用`numpy`首先要导入模块:

    ```python
    import numpy as np
    ```
    
    列表转化为矩阵:
    ```python
    array = np.array()
    ```
    
    使用以下命令查看矩阵属性：
    ```python
    array.ndim 查看维度
    array.shape 查看矩阵大小
    array.size 查看矩阵元素个数
    ```
****************

## 在numpy中创建array

## 关键字
```python
array:创建数组
dtype:指定数据类型
zeros:创建数据类型全为0
ones:创建数据类型全为1
empty:创建数据类型接近0
arrange:按指定范围创建数据
linspace:创建等间隔线段
```

In [9]:
import numpy as np
a = np.array([2,23,4])
print(a)

[ 2 23  4]


In [11]:
a = np.array([2,23,4],dtype = np.int64)
print(a.dtype)
a = np.array([2,23,4],dtype = np.int32)
print(a.dtype)
a = np.array([2,23,4],dtype = np.float)
print(a.dtype)
a = np.array([2,23,4],dtype = np.float32)
print(a.dtype)

int64
int32
float64
float32


In [22]:
a = np.array([[2,23,4],[2,32,4]])
print(a)
a = np.zeros((3,4))
print(a)
a = np.ones((3,4),dtype = np.int)
print(a)
a = np.empty((3,4))
print(a)
a = np.arange(10,20,2)
print(a)
a = np.arange((12)).reshape((3,4))
print(a)
a = np.linspace(1,10,20)
print(a)
a = np.linspace(1,10,20).reshape((4,5))
print(a)

[[ 2 23  4]
 [ 2 32  4]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[10 12 14 16 18]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[[ 1.          1.47368421  1.94736842  2.42105263  2.89473684]
 [ 3.36842105  3.84210526  4.31578947  4.78947368  5.26315789]
 [ 5.73684211  6.21052632  6.68421053  7.15789474  7.63157895]
 [ 8.10526316  8.57894737  9.05263158  9.52631579 10.        ]]
